version: '3'
services:

  # MySQL Service
  db:
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    image: "mysql:${MYSQL_IMAGE_VERSION}"
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    tty: true
    ports:
      - "33061:3306"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/files/:/var/lib/mysql-files
      - ./mysql/etc/my.cnf:/etc/mysql/my.cnf
